// AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_oldschool_cga_8x8_H
#define METASPRITE_oldschool_cga_8x8_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define oldschool_cga_8x8_TILE_ORIGIN 0
#define oldschool_cga_8x8_TILE_W 8
#define oldschool_cga_8x8_TILE_H 8
#define oldschool_cga_8x8_WIDTH 256
#define oldschool_cga_8x8_HEIGHT 64
#define oldschool_cga_8x8_TILE_COUNT 256
#define oldschool_cga_8x8_MAP_ATTRIBUTES 0
extern const unsigned char oldschool_cga_8x8_map[256];
#define oldschool_cga_8x8_map_attributes oldschool_cga_8x8_map

BANKREF_EXTERN(oldschool_cga_8x8)

extern const uint8_t oldschool_cga_8x8_tiles[2048];

#endif
